language: bash

sudo: required

before_install:
        - apt-get update
        - apt-get install -y shellcheck

script:
        - bash test.sh

notifications:
        email:
                on_success: never
