language: bash

before_install:
        - sudo apt-get update
        - sudo apt-get install -y shellcheck

script:
        - bash test.sh

notifications:
        email:
                on_success: never